config/routes.rb
Mailer::Application.routes.draw do
  root :to => redirect('/mail')
  get 'mail' => 'custom_mail#index'
  post 'mail' => 'custom_mail#deliver'
  get 'mail/check_delivery' => 'custom_mail#check_delivery'

end

app/models/job_state.rb
class JobState < ActiveRecord::Base
  attr_accessible :completion
end

app/models/letter.rb
class Letter
  attr_accessor :subject, :text, :image
  
  def initialize(subject, text, image)
    @subject = subject
    @text = text
    @image = image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/custom_mail_controller.rb
class CustomMailController < ApplicationController
  def index
    respond_to do |format|
      format.html
    end
  end

  def deliver
    image = params[:image] && { 'name' => params[:image].original_filename, 'content' => params[:image].read }
    letter = Letter.new(params[:subject], params[:text], image)
    
    @job_state = JobState.new(completion: 0)
    @job_state.save

    job = Delayed::Job.new
    job.handler = MailingJob.new(letter, @job_state.id)
    job.save

    respond_to do |format|
      format.js 
    end
  end

  def check_delivery
    @completion = JobState.find(params[:job_state_id]).completion

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
  def index
    respond_to do |format|
      format.html
    end
  end

  def deliver
    image = params[:image] && { 'name' => params[:image].original_filename, 'content' => params[:image].read }
    letter = Letter.new(params[:subject], params[:text], image)
    
    @job_state = JobState.new(completion: 0)
    @job_state.save

    job = Delayed::Job.new
    job.handler = MailingJob.new(letter, @job_state.id)
    job.save

    respond_to do |format|
      format.js 
    end
  end

  def check_delivery
    @completion = JobState.find(params[:job_state_id]).completion

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mail_controller_helper.rb
module MailControllerHelper
end

app/views/custom_mail/_progress_bar_delivered.html.haml
.alert.alert-success
  Mail has been delivered.
  
.progress.progress-striped
  #delivery-bar.bar-success.bar{ style: "width: 100%;" }

= link_to "Send another mail", mail_path, class: "btn btn-primary btn-large"

app/views/custom_mail/_progress_bar_delivering.html.haml
.alert.alert-info
  Mail is currently being delivered.

.progress.progress-striped.active
  #delivery-bar.bar{ style: "width: #{completion}%;" }

app/views/custom_mail/check_delivery.js.erb
var completion = <%= @completion %>
document.getElementById('delivery-bar').style.width = completion + '%';

if(completion == 100) {
  $('#delivery-info').html('<%= j(render("progress_bar_delivered")) %>');
}
else {
  setTimeout(checkDelivery, 1000);
}

app/views/custom_mail/deliver.js.erb
var controls = $(".controls :input");
var i;
for (i = 0; i < controls.length; i++) {
  controls[i].disabled = true;
}
$('#image-upload a').addClass('disabled');
$('#image-upload a').unbind();
$('#delivery-info').html('<%= j(render("progress_bar_delivering", completion: 0)) %>');

document.getElementById('delivery-info').setAttribute('job-state-id', '<%= @job_state.id %>');
setTimeout(checkDelivery, 1000);

function checkDelivery() {
  var job_state_id = document.getElementById('delivery-info').getAttribute("job-state-id");
  $.get("/mail/check_delivery.js?job_state_id=" + job_state_id)
};

app/views/custom_mail/index.html.haml
.span8.offset2
  = form_tag({ action: :deliver, controller: :custom_mail }, method: :post, remote: true, multipart: true) do
    .row
      .control-group
        %h4.control-label Subject
        .controls
          = text_field_tag(:subject, nil, class: 'span5')
    .row
      .control-group
        %h4.control-label Text
        .controls
          = text_area_tag(:text, nil, rows: 10, class: 'span8')
    .row 
      .control-group
        %h4.control-label Upload image
        .controls
          #hidden-image-upload.hidden= file_field_tag(:image, accept: 'image/*')
          #image-upload.input-append
            %p.input.uneditable-input No file chosen
            = link_to('Select', 'javascript:void(0);', class: 'btn')
    
    .row
      #delivery-info
        = submit_tag('Send mail', remote: true, class: 'btn btn-primary btn-large', id: 'submit-button')

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Mailer"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    -#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    -#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    -#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    -#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    -#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-static-top.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .row
            .offset5
              %a.brand{ style: "margin:0 auto;" } 
                %h2 Mailer

    %div{ id: "fix-for-navbar-fixed-top-spacing", style: "height: 30px;"}
    .container

      .row
        = bootstrap_flash
        = yield
    
      %footer
        %br
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"